escape_output_instead_of_sanitize: true
graphql_argument_type_mismatch_mode: error
liquid_check_mode: error
liquid_raise_mode: true
require_table_for_record_delete_mutation: true
safe_translate: true
slug_exact_match: true
websockets_require_csrf_token: true
sync_assets: true
maintenance:
  enabled: false
  password_constant: 'MAINTENANCE_PASSWORD'
  partial: 'maintenance'
