# -*- http -*-
PUT https://partner-template.staging-oregon.near-me.com/api/user/transactables/20297
Authorization: Token token=8e164104a090926fb84f822b6c27afb1a825b497
Accept: application/json
Content-Type: application/json

{
  "form_configuration_name": "team",
  "form": {
    "name": "Example1"
  }
}

# -*- http -*-
PUT http://documentation.lvh.me:3000/api/user/transactables/19583
Authorization: Token token=f54a9fd5b3c05d785a48b20e1e978e75a57283d5
Accept: application/json
Content-Type: application/json

{
  "form_configuration_name": "reference_rest_api_transactable_update",
  "form":
    "name": "Example"
  }
}



# -*- http -*-
POST http://documentation.lvh.me:3000/api/sessions
Authorization: Token token=192a8aee2e9c3bbd20e4e207506926c0
Accept: application/json
Content-Type: application/json

{
  "form_configuration_name": "reference_rest_api_create_session",
  "form": {
    "email": "existing_user@platformos.com",
    "password": "somepassword"
  }
}


# -*- http -*-
DELETE http://documentation.lvh.me:3000/api/sessions
Authorization: Token token=192a8aee2e9c3bbd20e4e207506926c0
Accept: application/json
Content-Type: application/json

{
  "form_configuration_name": "reference_rest_api_delete_session"
}


# -*- http -*-
POST http://documentation.lvh.me:3000/api/user/transactables
Authorization: Token token=192a8aee2e9c3bbd20e4e207506926c0
Accept: application/json
Content-Type: application/json

{
  "form_configuration_name": "reference_rest_api_create_transactable",
  "parent_resource_id": "boat",
  "form": {
    "name": "My boat",
    "creator_id": 123455
  }
}
